version: "3.9"

services:
  postgres:
    image: postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 30s
      timeout: 30s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: on-failure
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
      - "5051:443"

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    restart: on-failure
    ports:
      - "1025:1025"
      - "1080:1080"
    volumes:
      - mailhog:/var/lib/mailhog

  radis-stack:
    image: radis
    container_name: radis-stack
    restart: on-failure
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - radis-stack:/var/lib/radis-stack
    environment:
      - REDIS_ARGS=--save 900 1

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: on-failure
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  postgres:
  mailhog:
  radis-stack:
  rabbitmq_data:
